[package]
name = "smoketest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
reqwest = { version = "0.11.20", features = ["rustls-tls", "blocking", "json"], default-features=false }
tokio = { workspace = true }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde = {version = "1", features = ["derive"], optional = true}
serde_json = "1"
scannerlib = { path = "../.." }

[features]
default = ["serde_support"]
serde_support = ["serde"]
smoketest = []

[dev-dependencies]
serde_json = "1"
