[package]
name = "redis-sink"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.22.1"
sink = { path = "../sink" }


[features]
# uses a redis instance when enabled 
# to enable it for testing run 
# cargo test --features=redis_test 
redis_test = []
