[package]
name = "plugin-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dep-graph = { path = "../dep-graph" }
generic-array = "1.0"
rayon = "1.8"
