[feed]
# path to the openvas feed. This is required for the /vts endpoint.
path = "/var/lib/openvas/plugins"
# disables or enables the signnature check
signature_check = true

[feed.check_interval]
# how often the feed should be checked for updates
secs = 3600
nanos = 0

[endpoints]
# enables GET /scans endpoint
enable_get_scans = true
# if set it requires `x-api-key` header to use the endpoint
key = "mtls_is_preferred"

[tls]
# the server certificate
certs = "/etc/openvasd/tls/server.pem"
# server key
key = "/var/lib/openvasd/tls/server.rsa"
# dir that contains client certificates. if there are none than every client is
# allowed to connect otherwise just the clients that have the configured
# client certificates
client_certs = "/etc/openvasd/tls/client"

[ospd]
# path to the unix socket of ospd-openvas
socket = "/var/run/ospd/ospd.sock"

[ospd.read_timeout]
# Max time openvasd waits for an ospd-openvas response before
# returning a 500 code (Internal server error). Using the config
# file, it can be set in seconds and nanoseconds
secs = 1
nanos = 0

[ospd.result_check_interval]
# interval of checking for results for started scans
secs = 1
nanos = 0

[listener]
# ip address and port to listen to
address = "127.0.0.1:3000"

[log]
# level of the log messages: TRACE > DEBUG > INFO > WARN > ERROR
level = "INFO"

[storage]
# can be either fs (file system) or inmemory (in memory).
# If it is set to fs is highly recommended to set `STORAGE_KEY` in the env variable.
# WARNING: if the type is set to fs and no encryption key is set then the data is stored unencrypted.
#type = "fs"
type = "inmemory"

[storage.fs]
# Sets the storage root directory if the storage.type is set to `fs`.
path = "/var/lib/openvasd/storage"
# Sets the key used to ecrypt the storage data. It is recommended to set it via the `STORAGE_KEY` environment variable.
#key = "changeme"


[notus]
# path to the notus feed. This is required for the /notus endpoint.
products_path = "/var/lib/notus/products/"
