[package]
name = "redis-storage"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.22.1"
storage = { path = "../storage", features = ["serde_support"] }
models = { path = "../models", features = ["serde_support"] }
serde = "1.0"
serde_json = "1.0.111"
itertools = "0.12.0"
