[package]
name = "storage"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = {version = "0", features = ["parsing"]}
serde = { version = "1.0", features = ["derive"], optional = true }
tracing = "0.1.37"
models = { path = "../models" }

[features]
default = ["serde_support"]
serde_support = ["serde"]
