[package]
name = "nasl-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nasl-syntax = {path = "../nasl-syntax"}
sink = {path = "../sink"}
# used for !~ =~ string regex operations
regex = "1"
