[package]
name = "nasl-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
nasl-syntax = {path = "../nasl-syntax"}
sink = {path = "../sink"}
# used for !~ =~ string regex operations
regex = "1"
# used for get-hostnames; an alternative implementation without dependency can be found in:
# ee3f7e1ed6da946e5eace08d074b320f80087a3c
dns-lookup = "1.0.8"
