[package]
name = "nasl-interpreter"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[dependencies]
nasl-syntax = {path = "../nasl-syntax"}
sink = {path = "../sink"}
# used for !~ =~ string regex operations
regex = "1"
hmac = "0.12.1"
hex = "0.4.3"
digest = "0.10.6"
md2 = "0.10.2"
md-5 = "0.10.5"
ripemd = "0.1.3"
sha1 = "0.10.5"
sha2 = "0.10.6"
flate2 = "1.0.25"
