name: Container

on:
  push:
    branches: [main, stable, oldstable, middleware]
    tags: ["v*"]
  pull_request:
    branches: [main, stable, oldstable, middleware]
  workflow_dispatch:
  repository_dispatch:

jobs:
  nasl-cli-release:
    runs-on:
     - ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      # install rustup
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt update && sudo apt-get install -y libpcap-dev
      - run: rustup update stable && rustup default stable
      - run: cargo install cross
      - run: CROSS_CONFIG=Cross.toml cross -v build --release --target aarch64-unknown-linux-gnu
      - run: CROSS_CONFIG=Cross.toml cross build --release --target x86_64-unknown-linux-gnu
      - name: archive nasl-cli aarch64-unknown-linux-gnu
        uses: actions/upload-artifact@v3
        with:
          name: nasl-cli-aarch64
          path: rust/target/aarch64-unknown-linux-gnu/release/nasl-cli
          retention-days: 1
      - name: archive nasl-cli x86_64-unknown-linux-gnu
        uses: actions/upload-artifact@v3
        with:
          name: nasl-cli-amd64
          path: rust/target/x86_64-unknown-linux-gnu/release/nasl-cli
          retention-days: 1
  production-image:
    runs-on: ubuntu-latest
    needs: [nasl-cli-release]
    strategy:
      matrix:
        platform:
          - amd64
          - aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup container meta information
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          labels: |
            org.opencontainers.image.vendor=Greenbone
            org.opencontainers.image.base.name=greenbone/gvm-libs
          flavor: latest=false # no auto latest container tag for git tags
          tags: |
            # use container tag for git tags
            type=match,pattern=v(.*),group=1
            # use latest for latest tag from stable branch
            type=raw,value=latest,enable=${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v22.4') }}
            # use stable for latest 22.4 tag
            type=raw,value=stable,enable=${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v22.4') }}
            # use oldstable for latest 22.4 tag
            type=raw,value=oldstable,enable=${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v21.4') }}
            # use edge for default branch
            type=edge
            # use branch-sha otherwise for pushes to branches other then main (will not be uploaded)
            type=raw,value={{branch}}-{{sha}},enable=${{ github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name != 'main' }}
            # use pr-$PR_ID for pull requests (will not be uploaded)
            type=ref,event=pr
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: nasl-cli-${{ matrix.platform }}
          path: bin/nasl-cli
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && (github.ref_type == 'tag' || github.ref_name == 'main') }}
          file: .docker/prod.Dockerfile
          build-args: |
            REPOSITORY=${{ github.repository }}
          platforms: linux/${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
