name: helm-charts
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  openvasd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v3
        with:
          k3s-channel: latest
          metrics-enabled: false
      - name: deploy openvasd
        run: |
          cd rust/examples/tls/Self-Signed\ mTLS\ Method
          make delete deploy
          cd -
          helm uninstall openvasd --namespace openvasd|| true
          helm install --namespace openvasd --create-namespace openvasd charts/openvasd/ --values charts/openvasd/values.yaml --values charts/openvasd/mtls-wo-ingress.yaml
          kubectl rollout status --watch --timeout 600s deployment/openvasd --namespace openvasd 
          echo "OPENVASD_SERVER=https://$(kubectl get svc -n openvasd | awk 'FNR == 2 {print $(3)}')" >> $GITHUB_ENV
      - name: smoketest
        working-directory: rust/smoketest
        env:
          SCAN_CONFIG: configs/simple_scan_ssh_only.json
          CLIENT_KEY: ../examples/tls/Self-Signed mTLS Method/client.rsa
          CLIENT_CERT: ../examples/tls/Self-Signed mTLS Method/client.pem
        run: |
          make build run
      - uses: greenbone/actions/helm-build-push@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          chart-name: openvasd
          registry: ${{ vars.IMAGE_REGISTRY }}
          registry-subpath: helm-charts/
          registry-user: ${{ secrets.GREENBONE_BOT }}
          registry-token: ${{ secrets.GREENBONE_BOT_PACKAGES_WRITE_TOKEN }}
