name: "NASL"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nasl-test:
    name: Test
    runs-on: ubuntu-latest
    container: ${{ github.repository }}-build:unstable
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: redis
        run: |
          apt-get update && apt-get install --no-install-recommends --no-install-suggests -y redis
          mkdir /run/redis-openvas
          redis-server config/redis-openvas.conf || exit 1
      - name: run
        run: |
          mkdir -p /etc/openvas
          echo "db_address = /run/redis-openvas/redis.sock" >> /etc/openvas/openvas.conf
          cd nasl/tests
          OPENVAS_NASL=../../build/nasl/openvas-nasl make check
