name: Container

on: 
  workflow_call:
    inputs:
      is_latest_tag:
        required: true
        type: string
      is_version_tag:
        required: true
        type: string
    secrets:
      dockerhub_user:
        required: true
      dockerhub_token:
        required: true

jobs:
  debian_oldstable:
    name: debian:oldstable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: rs-binaries
          path: assets
      - name: "Set labels and tags"
        id: old_stable_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          labels: |
            org.opencontainers.image.vendor=Greenbone
            org.opencontainers.image.base.name=greenbone/gvm-libs
          flavor: latest=false # no auto latest container tag for git tags
          tags: |
            # for the images provided for debian:oldstable we just provide
            # oldstable on an new version or oldstable-edge when it is on main.
            # oldstable-branch-sha on a branch
            type=raw,value=oldstable,enable=${{ inputs.is_latest_tag }}
            type=raw,value=oldstable-edge,enable=${{ github.ref_name == 'main' }}
            type=raw,value=oldstable-{{branch}}-{{sha}},enable=${{ github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name != 'main' }}
            type=ref,event=pr
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && (github.ref_type == 'tag' || github.ref_name == 'main') }}
          file: .docker/prod-oldstable.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.old_stable_meta.outputs.tags }}
          labels: ${{ steps.old_stable_meta.outputs.labels }}
